### ISSUE TITLE
Script istatserver is broken: incomplete LSB comment

### ISSUE THREAD

**Issue by Thireus** [citrus/iStat-Server-Installer#1]
# sudo update-rc.d istatserver defaults

update-rc.d: using dependency based boot sequencing
insserv: Script istatserver is broken: incomplete LSB comment.
insserv: missing `Required-Start:' entry: please add even if empty.
insserv: missing`Required-Stop:'  entry: please add even if empty.
insserv: missing `Default-Start:'  entry: please add even if empty.
insserv: missing`Default-Stop:'   entry: please add even if empty.
insserv: Default-Start undefined, assuming empty start runlevel(s) for script `istatserver'
insserv: Default-Stop  undefined, assuming empty stop  runlevel(s) for script`istatserver'

**Comment by citrus** [comment]
What OS are you on?

**Comment by Thireus** [comment]
Debian 6.0

**Comment by citrus** [comment]
The init.d script was created for Ubuntu systems only. I know debian and ubuntu are very similar, but I'm not familiar with the differences regarding init scripts. If you can create a fix I'd be happy to add it to the repository.

**Comment by duecedriver** [comment]
getting the same errors in ubuntu 16-04 server

openflixr@openflixr:/etc/init.d$ sudo chmod +x /etc/init.d/istatserver
openflixr@openflixr:/etc/init.d$ sudo update-rc.d istatserver defaults
insserv: Script istatserver is broken: incomplete LSB comment.
insserv: missing `Required-Start:' entry: please add even if empty.
insserv: missing `Required-Stop:'  entry: please add even if empty.
insserv: missing `Default-Start:'  entry: please add even if empty.
insserv: missing `Default-Stop:'   entry: please add even if empty.
insserv: Default-Start undefined, assuming empty start runlevel(s) for script `istatserver'
insserv: Default-Stop  undefined, assuming empty stop  runlevel(s) for script `istatserver'
